inputValues = input("input comma separated values to be printed as list and tuple: ")
outputList = inputValues.split(",")
outputTuple = tuple(outputList)
print("input as list:", outputList)
print("input as tuple", outputTuple)
